python filter_properties.py moda_nrc_plus_ote_files.list --outfile nircam_modA_plus_ote_filter_properties.txt
python filter_properties.py modb_nrc_plus_ote_files.list --outfile nircam_modB_plus_ote_filter_properties.txt

python filter_properties.py modabmean_nrc_plus_ote_files.list --outfile nircam_modABmean_plus_ote_filter_properties.txt


